version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0

executors:
  arm-executor:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium

jobs:
  deploy-dynamic:
    executor: arm-executor
    steps:
      - checkout
      - run:
          name: Install jq
          command: sudo apt-get install -y jq
      - run:
          name: Install yq
          command: |
            sudo wget https://github.com/mikefarah/yq/releases/download/v4.30.5/yq_linux_amd64 -O /usr/bin/yq
            sudo chmod +x /usr/bin/yq

      - aws-cli/setup:
          profile_name: "default"  # Se usa un perfil temporal antes de que el script configure dinámicamente.
      - run:
          name: Parse and Deploy Configurations
          command: |
            chmod +x ./scripts/parse_deploy_config.sh
            ./scripts/parse_deploy_config.sh

workflows:
  iac-compute:
    jobs:
      - deploy-dynamic