version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/workspace

jobs:
  deploy-vpc:
    executor: default
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Deploy VPC using script
          command: |
            chmod +x ./scripts/deply.sh
            ./scripts/deply.sh templates/VPC.yml my-vpc

workflows:
  version: 2
  vpc-deploy:
    jobs:
      - deploy-vpc:
          context: 
            - region
            - idaws
            - clavaws

