version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0

executors:
  arm-executor:
    machine:
      image: cimg/base:stable 
    resource_class: arm.medium

jobs:
  deploy-dynamic:
    executor: arm-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get install -y jq yq
      - aws-cli/setup:
          profile_name: "default"  # Se usa un perfil temporal antes de que el script configure dinámicamente.
      - run:
          name: Parse and Deploy Configurations
          command: |
            chmod +x ./scripts/parse_deploy_config.sh
            ./scripts/parse_deploy_config.sh

workflows:
  iac-compute:
    jobs:
      - deploy-dynamic