version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8

jobs:
  create-vpc:
    executor: default
    context: región 
    steps:
      - checkout
      - run:
          name: Verificar variables de entorno
          command: |
            echo "AWS_REGION: $AWS_REGION"
            echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
            echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
      - run:
          name: Instalar AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: Crear una VPC en AWS
          command: |
            aws ec2 create-vpc --cidr-block 10.0.0.0/16 --region $AWS_REGION
            #nueva
            #OTRA
workflows:
  version: 2
  create-vpc-workflow:
    jobs:
      - create-vpc:
          context: región
