AWSTemplateFormatVersion: '2010-09-09'
Description: 'Peering entre MiVPC y MiNuevaVPC'

Resources:
  # VPC Peering Connection
  VPCPeeringConnection:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties:
      VpcId: !ImportValue MiVPC               # Importa el ID de MiVPC
      PeerVpcId: !ImportValue MiNuevaVPC       # Importa el ID de MiNuevaVPC
      PeerRegion: !Ref "AWS::Region"
      Tags:
        - Key: Name
          Value: VPCPeeringMiVPC_MiNuevaVPC

  # Ruta en MiVPC hacia MiNuevaVPC
  MiVPCRouteTable:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !ImportValue MiVPCRouteTableId         # Importa el ID de la tabla de rutas de MiVPC
      DestinationCidrBlock: "{{resolve:ssm:/miapp2/vpc/cidr}}" # CIDR de MiNuevaVPC
      VpcPeeringConnectionId: !Ref VPCPeeringConnection

  # Ruta en MiNuevaVPC hacia MiVPC
  MiNuevaVPCRouteTable:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !ImportValue MiNuevaVPCRouteTableId    # Importa el ID de la tabla de rutas de MiNuevaVPC
      DestinationCidrBlock: "{{resolve:ssm:/miapp/vpc/cidr}}" # CIDR de MiVPC
      VpcPeeringConnectionId: !Ref VPCPeeringConnection

Outputs:
  VPCPeeringConnectionId:
    Description: 'ID de la conexión de Peering'
    Value: !Ref VPCPeeringConnection
